branch-defaults:
  main:
    environment: 21181946-PortfolioWeb-Env
    group_suffix: null
global:
  application_name: 22181946-PortfolioWebApp
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
