# Generated by Django 2.1.15 on 2023-04-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('portfolio_url', models.URLField()),
                ('portfolio_images', models.ManyToManyField(blank=True, to='portFolioApp.PortfolioImage')),
            ],
        ),
    ]
