# Generated by Django 2.1.15 on 2023-04-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portFolioApp', '0004_auto_20230422_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='portfolioregistration',
            name='portfolio_images',
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='registration',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='portFolioApp.PortfolioRegistration'),
        ),
    ]
